name: Build and Release BLE GUI

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed main.py

    - name: Rename artifact
      run: |
        mkdir dist_upload
        copy dist\\main.exe dist_upload\\BLETool-Windows.exe

    - name: Upload release artifact
      uses: softprops/action-gh-release@v2
      with:
        files: dist_upload/*
        token: ${{ secrets.GH_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  build-macos-arm:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt pyinstaller

    - name: Build for macOS arm64
      run: |
        pyinstaller --onefile --windowed main.py

    - name: Zip .app directory
      run: |
        mkdir dist_upload
        cd dist
        zip -r ../dist_upload/BLETool-macOS-arm64.zip main.app
        cd ..

    - name: Upload release artifact
      uses: softprops/action-gh-release@v2
      with:
        files: dist_upload/*
        token: ${{ secrets.GH_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  build-macos-intel:
    runs-on: [self-hosted, macOS, X64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt pyinstaller

    - name: Build for macOS x86_64
      run: |
        pyinstaller --onefile --windowed main.py

    - name: Zip .app directory
      run: |
        mkdir dist_upload
        cd dist
        zip -r ../dist_upload/BLETool-macOS-x86_64.zip main.app
        cd ..

    - name: Upload release artifact
      uses: softprops/action-gh-release@v2
      with:
        files: dist_upload/*
        token: ${{ secrets.GH_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
