name: Build and Release BLE GUI

on:
  push:
    tags:
      - 'v*'   # 推送 v1.0.0 类 tag 时触发

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            runner_label: windows-latest
            suffix: .exe
          - os: macos-latest
            runner_label: macos-latest
            suffix: .app
          - os: self-hosted
            runner_label: [self-hosted, macOS, X64]
            suffix: .app
            name: macos-intel

    runs-on: ${{ matrix.runner_label }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed main.py

    - name: Rename artifact
      run: |
        mkdir dist_upload
        if [[ "${{ matrix.suffix }}" == ".exe" ]]; then
          cp dist/main.exe dist_upload/BLETool-${{ runner.os }}${{ matrix.suffix }}
        else
          cd dist
          zip -r ../dist_upload/BLETool-${{ runner.os }}.zip ./
          cd ..
        fi
      shell: bash

    - name: Upload release artifact
      uses: softprops/action-gh-release@v2
      with:
        files: dist_upload/*
        token: ${{ secrets.GH_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
